name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  macos-latest-stable:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2    
      - name: install elm
        run: |
          npm install elm
      - name: build
        run: |
          ./node_modules/elm/bin/elm make
      - name: build docs
        run: |
          ./node_modules/elm/bin/elm make --docs=docs.json        
      - name: install elm-format
        run: |
          npm install elm-format
      - name: format
        run: |
          ./node_modules/elm-format/bin/elm-format src --validate          
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test


  windows-latest-stable:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2    
      - name: install elm
        run: |
          npm install elm
      - name: build
        run: |
          ./node_modules/elm/bin/elm make
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test

  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2    
      - name: install elm
        run: |
          npm install elm
      - name: build
        run: |
          ./node_modules/elm/bin/elm make
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test