name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  macos-latest-stable:
    runs-on: macos-latest
    steps:
      - name: setup elm
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: build
        run: |
          elm make
      - name: build docs
        run: |
          elm make --docs=docs.json        
      - name: install elm-format
        run: |
          npm install elm-format
      - name: format
        run: |
          ./node_modules/elm-test/bin/elm-format src --validate          
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test


  windows-latest-stable:
    runs-on: windows-latest
    steps:
      - name: setup elm
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: build
        run: |
          elm make
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test

  windows-latest-nightly:
    runs-on: windows-latest
    steps:
      - name: setup elm
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: build
        run: |
          elm make
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test

  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: setup elm
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: build
        run: |
          elm make
      - name: install elm-test
        run: |
          npm install elm-test
      - name: test
        run: |
          ./node_modules/elm-test/bin/elm-test
          command: test